name: Terraform deploy

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
    terraform:
        uses: ./.github/workflows/deploy-aws.yml
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        with:
          root-module: test
          tfcloud-project: bartosz_org
          region: ap-southeast-2
          working-directory: "./terraform"
          workspace-name: terraform_sandbox
          